#!/bin/bash

# AWS Amplify Setup Script
# This script helps configure AWS Amplify for the Customer Portal

set -e

echo "🚀 AWS Amplify Setup for Customer Portal"
echo "=========================================="
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI is not installed. Please install it first:"
    echo "   https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
    exit 1
fi

echo "✅ AWS CLI is installed"
echo ""

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Please run 'aws configure' first."
    exit 1
fi

echo "✅ AWS credentials configured"
echo ""

# Prompt for environment
echo "Select environment to configure:"
echo "1) Production"
echo "2) Staging"
echo "3) Both"
read -p "Enter choice (1-3): " env_choice

case $env_choice in
    1)
        ENVIRONMENTS=("production")
        ;;
    2)
        ENVIRONMENTS=("staging")
        ;;
    3)
        ENVIRONMENTS=("production" "staging")
        ;;
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac

# Function to collect environment variables
collect_env_vars() {
    local env=$1
    echo ""
    echo "📝 Configuring $env environment"
    echo "================================"
    
    read -p "Auth0 Domain: " AUTH0_DOMAIN
    read -p "Auth0 Client ID: " AUTH0_CLIENT_ID
    read -p "Auth0 Audience: " AUTH0_AUDIENCE
    read -p "API URL: " API_URL
    read -p "Stripe Publishable Key: " STRIPE_KEY
    
    echo ""
    echo "Environment variables for $env:"
    echo "VITE_AUTH0_DOMAIN=$AUTH0_DOMAIN"
    echo "VITE_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID"
    echo "VITE_AUTH0_AUDIENCE=$AUTH0_AUDIENCE"
    echo "VITE_API_URL=$API_URL"
    echo "VITE_STRIPE_PUBLISHABLE_KEY=$STRIPE_KEY"
    echo ""
    
    read -p "Save these to .env.$env.local? (y/n): " save_choice
    if [ "$save_choice" = "y" ]; then
        cat > ".env.$env.local" <<EOF
# $env Environment Configuration
# Generated by setup-amplify.sh on $(date)

VITE_AUTH0_DOMAIN=$AUTH0_DOMAIN
VITE_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
VITE_AUTH0_AUDIENCE=$AUTH0_AUDIENCE
VITE_API_URL=$API_URL
VITE_STRIPE_PUBLISHABLE_KEY=$STRIPE_KEY
NODE_ENV=$env
EOF
        echo "✅ Saved to .env.$env.local"
    fi
}

# Collect variables for each environment
for env in "${ENVIRONMENTS[@]}"; do
    collect_env_vars "$env"
done

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Go to AWS Amplify Console: https://console.aws.amazon.com/amplify/"
echo "2. Create a new app and connect your Git repository"
echo "3. Add the environment variables shown above in App Settings → Environment Variables"
echo "4. Deploy your application"
echo ""
echo "For detailed instructions, see DEPLOYMENT.md"
